version: 2

project_name: LYRA

before:
  hooks:
    - go mod tidy

builds:
  - id: lyra
    main: ./cmd/lyra
    binary: lyra

    goos:
      - linux

    goarch:
      - amd64

archives:
  - id: default
    formats: [tar.gz]
    files:
      - README.md
      - LICENSE

checksum:
  name_template: checksums.txt

release:
  draft: false