name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            binary: lyra-linux-amd64

          - goos: linux
            goarch: arm64
            binary: lyra-linux-arm64

          - goos: windows
            goarch: amd64
            binary: lyra-windows-amd64.exe

          - goos: darwin
            goarch: amd64
            binary: lyra-macos-intel

          - goos: darwin
            goarch: arm64
            binary: lyra-macos-apple

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.26'

      - run: |
          GOOS=${{ matrix.goos }} \
          GOARCH=${{ matrix.goarch }} \
          go build -ldflags="-s -w" \
          -o ${{ matrix.binary }} \
          ./cmd/lyra

      - uses: softprops/action-gh-release@v2
        with:
          files: ${{ matrix.binary }}